# Generated by Django 5.2 on 2025-05-09 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiped_date', models.DateTimeField(blank=True, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('date_payed', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('pending', 'PEDING'), ('processing', 'PROCESSING'), ('cancelled', 'CANCELLED'), ('delivered', 'DELIVERED')], default='pending')),
                ('amount', models.IntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
