# Generated by Django 5.2 on 2025-05-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
