# Generated by Django 5.2 on 2025-05-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
