# Generated by Django 5.2 on 2025-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, null=True),
        ),
    ]
