# Generated by Django 5.2 on 2025-05-13 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0009_alter_paypalipn_id'),
        ('payment', '0010_remove_order_uid_order_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipn.paypalipn')),
            ],
        ),
    ]
