# Generated by Django 5.2 on 2025-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
