# Generated by Django 5.2 on 2025-05-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_order_payer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
