# Generated by Django 5.2 on 2025-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
