# Generated by Django 5.2 on 2025-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment_rating_wishedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_rating',
            field=models.IntegerField(default=0),
        ),
    ]
